IMAGE_WIDTH = 28
IMAGE_HEIGHT = 28
CHANNELS = 1
INPUT_SHAPE = (IMAGE_WIDTH, IMAGE_HEIGHT, CHANNELS)

MARGIN = 0.5
EMBEDDING_SIZE = 2
LR = 0.0001

NUM_CLASSES = 10
EPOCHS = 10
TRAIN_TRIPLES = NUM_CLASSES * (NUM_CLASSES - 1) * 15
BATCH_SIZE = 32
