IMAGE_WIDTH = 28
IMAGE_HEIGHT = 28
CHANNELS = 1
INPUT_SHAPE = (IMAGE_WIDTH, IMAGE_HEIGHT, CHANNELS)

MARGIN = 0.5
EMBEDDING_SIZE = 25
LR = 0.0001
SEMI_HARD_IMG_COUNT = 1000

NUM_CLASSES = 10
TRAIN_TRIPLES = NUM_CLASSES * (NUM_CLASSES - 1) * 1
EPOCHS = 10
EPOCHS_PER_BATCH = 5
BATCH_SIZE = 16
