IMAGE_WIDTH = 28
IMAGE_HEIGHT = 28
CHANNELS = 1
INPUT_SHAPE = (IMAGE_WIDTH, IMAGE_HEIGHT, CHANNELS)

MARGIN = 0.5
EMBEDDING_SIZE = 25

NUM_CLASSES = 10
EPOCHS = 5
TRAIN_TRIPLES = NUM_CLASSES * (NUM_CLASSES - 1) * 10
BATCH_SIZE = 32
